language: php

php:
  - 7.2
  - 7.3

# In case of timeouts and build failures you may want to prepend 'travis_retry' to the following commands:
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install -n

script:
  - php composer.phar test

after_script:
  - php composer.phar coverage
